### PR TITLE
Add MTG stuff

### PR DESCRIPTION
**Pull request by shawntanzk**
Note: the NS Forest file is in a odd format - its from the supp materials of the paper, what Richard sent over. All the information should still be there, but might need some reworking. 
Ideally the same GTF file for human would work (though its a big ideally)

### CODE REVIEW

**Comment by shawntanzk** [comment]
Need help generating the curation files etc. too

**Comment by hkir-dev** [comment]
Marker and template files are generated
- [Markers](https://github.com/obophenotype/brain_data_standards_ontologies/tree/Add-MTG/src/markers)
- [Dosdp templates](https://github.com/obophenotype/brain_data_standards_ontologies/tree/Add-MTG/src/patterns/data/default)
- [Robot templates](https://github.com/obophenotype/brain_data_standards_ontologies/blob/Add-MTG/src/templates/CS1908210.tsv)

@shawntanzk can you please check [allen makers](https://github.com/obophenotype/brain_data_standards_ontologies/blob/Add-MTG/src/markers/CS1908210_Allen_markers.tsv) and [curation file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/Add-MTG/src/patterns/data/default/CS1908210_class_curation.tsv) please.

**Comment by shawntanzk** [comment]
Think Allen Marker file needs me to curate stuff first. Will do that and get back to you to generate it properly :) 
Thanks

**Comment by shawntanzk** [comment]
@hkir-dev have curated the markers, projections, and CL mappings onto class_curation - all ready to go for generating allen marker files and i guess ontology
Thanks!

**Pull request merged**
