### PR TITLE
Create brainCellRegionMarker.yaml

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Comment by dosumis** [comment]
Hi @BAevermann - Please review this draft template for generating textual definitions.   

It has simple printf statements followed by an order lists of fillers.  When interpreted by DOSDP-tools, it will substitute the names of OWL classes when the IDs (Curies) of OWL classes are provided as vars via a TSV. For the markers, we will hack for now by passing a string of marker names.   

Let me know if not clear how this works.

The tricky thing is deciding how to roll the label (which markers to use?) and how to make clear the difference between the minimal marker list and the denormalised one.  I noticed in PCL you managed to choose a single marker to use in names.  For example

[NPFFR2-expressing human primary motor cortex glutamatergic neuron](https://bioportal.bioontology.org/ontologies/PCL/?p=classes&conceptid=http%3A%2F%2Fpurl.obolibrary.org%2Fobo%2FPCL_0000210&jump_to_nav=true) has these in the def " COL22A1, and LOC401134, and NPFFR2".    Wondering how you chose and whether we could, should be doing that here.


Note, the EquivalentClass expression is rolled separately in a ROBOT template.  This tracks the first part of the textual definition.   It might be useful to flag the axioms linking to minimal markers in some way, but we're not doing that yet.

**Comment by dosumis** [comment]
#43

**Comment by BAevermann** [comment]
@dosumis - I looked over the DOSDP template for definition and (perhaps) label, but I didnt see any specifics about the definition generation. Sorry if i missed it. 

The template converts the marker IDs into a symbol list, but I did not see a template for the actual definition. Did I miss that function? 

For the pCL, I choose one of the minimum markers to be in the label. At current, NS-Forest does not create a best single marker filtered result; however, that can be easily retrieved from the full results file. So we can add another .tsv file with best single marker for label production only? Just an idea...

b.

**Comment by dosumis** [comment]
Templates

```yaml
name:
  text: "%s expressing %s of %s (%s)"
  vars:
   - minimal_marker_list
   - gross_cell_type
   - brain_region
   - taxon

def:
  text: "A %s of the %s %s that expresses: %s. The minimal set of markers required for its identification is: %s"
  vars:
   - gross_cell_type
   - taxon
   - brain_region
   - denorm_marker_list
   - minimal_marker_list
 ```

vars named x_marker_list = string of marker names, comma delimited, with alphanumeric sort.

**Pull request closed without merging**
