### PR TITLE
Editing non taxonomy roots

### PR DESCRIPTION
**Pull request by shawntanzk**
Added a bunch of non-taxonomy nodes
Think it should be merged to master and ec-individual?
Happy for you to merge @hkir-dev 
Thanks

### CODE REVIEW

**Comment by hkir-dev** [comment]
CS202002013_91 is defined as non_taxonomy_roots, but it exists in the [dendrogram](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/CCN202002013.json). Is this a problem?

**Comment by hkir-dev** [comment]
same for: CS202002013_111, 112, 113, 209, 210, 212, 222

**Comment by shawntanzk** [comment]
> CS202002013_91 is defined as non_taxonomy_roots, but it exists in the [dendrogram](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/dendrograms/CCN202002013.json). Is this a problem?

I think everything that is below 232 is in the dendrogram, however, I've just added the above as they are not in the [class file](https://github.com/obophenotype/brain_data_standards_ontologies/blob/master/src/templates/CCN202002013_class.tsv). 

I thought, after discussion in ytd meeting, that this would curate the CL elements into those that I couldn't, but happy to remove them. How would I curate those on in that case @dosumis? Thanks

**Comment by dosumis** [comment]
> CS202002013_91 is defined as non_taxonomy_roots, but it exists in the dendrogram. Is this a problem?

Yep.  They should be curated in the _class table.  They should now appear there because of the new rule (hack) for when to create classes.

**Comment by shawntanzk** [comment]
great, ill delete this branch and not merge it then

**Pull request closed without merging**
