### PR TITLE
nomenclature_table updated

### PR DESCRIPTION
**Pull request by hkir-dev**
Nomenclature table (src/dendrograms/nomenclature_table_CCN202002013.csv) updated and related CCN202002013_non_taxonomy_classification.tsv regenerated

### CODE REVIEW

**Comment by shawntanzk** [comment]
@dosumis this is marking corticothalamic as ET which is technically not wrong, but its not ET in the way that is transcriptomically ET group if that makes sense? Not sure if it is alright?

**Comment by dosumis** [comment]
@shawntanzk  - assume your concerns resolved by your own changes?  Can we merge this?

**Comment by shawntanzk** [comment]
> @shawntanzk - assume your concerns resolved by your own changes? Can we merge this?

This will be solved by that fix, though the file changes here looks like it still puts the entries as ET-projecting -> they should be uncurated now. @hkir-dev does this need be remade or something?

**Comment by shawntanzk** [comment]
1) files have been updated
2) will switch to directly grabbing it from Allen repow

**Pull request closed without merging**
