### PR TITLE
Curate definitions

### PR DESCRIPTION
**Pull request by shawntanzk**
Related to #207 
Human not done yet, currently tricky cause some are missing defs just cause of missing NS forest
Putting as draft for now - we can merge in to see how it looks and changes can happen later too.

### CODE REVIEW

**Comment by hkir-dev** [comment]
resulting ontology is at: https://github.com/obophenotype/brain_data_standards_ontologies/blob/5e42ae9e79525da451971df4f14a988891591ec3/bdscratch-full.owl
If it is OK, we can merge this branch

**Comment by shawntanzk** [comment]
Currently, a bunch of 131 (human) terms still do not have defs due to NS forest issues.
Once NS forest issues are fixed, will relook at this again.
I wonder if it would be wise to add a SPARQL check that fails (or at least warns) on no defs?

**Comment by shawntanzk** [comment]
@hkir-dev will change DOSDP template to not need NS-forest to generate definitions 
@hkir-dev will add an additional column for cross-species text 
@shawntanzk curate the text " " to C terms

**Comment by hkir-dev** [comment]
Since yesterday we started updating templates in the cross-species branch, all new template updates are in there: https://github.com/obophenotype/brain_data_standards_ontologies/tree/cross_species/src/patterns/data/default

Is there anything that we should get from this branch?

**Comment by shawntanzk** [comment]
I'll move them over manually - everything will be changed anyway, will delete this draft PR once I've done it - useful for me to reference from here. Thanks

**Comment by shawntanzk** [comment]
actually, probably easier if i just redo it fresh from cross-species, will close this PR

**Pull request closed without merging**
