### PR TITLE
Added non_taxonomy_roots

### PR DESCRIPTION
**Pull request by shawntanzk**
Added mapping for non_taxonomy_roots 
See file for comments on some nodes
Might need a CL release for this to work properly 
Not sure if this should be merged to master or EC_individual, I've made this PR to master, but happy for you to merge to EC_individual or both too.

### CODE REVIEW

**Comment by dosumis** [comment]
Looks like you have a syntax error in your YAML file:

```
yaml.scanner.ScannerError: while scanning for the next token
found character '\t' that cannot start any token
  in "/__w/brain_data_standards_ontologies/brain_data_standards_ontologies/src/config/../dendrograms/taxonomy_details.yaml", line 68, column 28
```

Maybe open in Atom to see if syntax highlighting flags anything.

(BTW - tests will not pass until updated schema is in place. @hkir-dev is doing that.)

**Comment by shawntanzk** [comment]
hmm strange, I can't find anything wrong with it. I've cleaned up the comment indentation (shouldn't affect either way) so I can get a clearer look and seems all ok. ATOM colours everything correctly too. Yeah I figured the checks were failing cause it needed an update, which was why I didn't really look into it.

**Comment by hkir-dev** [comment]
schema updated, validation is ok

**Review by dosumis — APPROVED** [review]

**Review by hkir-dev — APPROVED** [review]

**Comment by shawntanzk** [comment]
@hkir-dev I'll leave you to merge it to whichever branch etc. yeah

**Pull request merged**
