### PR TITLE
Create brainCellRegionMinimalMarkers.yaml

### PR DESCRIPTION
**Pull request by dosumis**

### CODE REVIEW

**Comment by dosumis** [comment]
Passes schema validator

**Comment by dosumis** [comment]
File is in wrong place.  Needs to be moved under `patterns/dosdp-patterns` !!

**Comment by hkir-dev** [comment]
is species = taxon?

**Comment by dosumis** [comment]
> is species = taxon?

Yes.  We should probably change to taxon though, as we have one example of a mixed species dendrogram where I'm using NCBI taxon = 'eutherian mammals ',  a broader taxonomic grouping than species.

**Comment by dosumis** [comment]
@hkir, is this the fixed version?

**Comment by hkir-dev** [comment]
No, fixed version is at https://github.com/obophenotype/brain_data_standards_ontologies/blob/ec_individuals/src/patterns/dosdp-patterns/brainCellRegionMinimalMarkers.yaml
We can merge this change to master with a ec_individuals branch pull request. We can close this pull request without merge.

**Comment by dosumis** [comment]
Now redundant

**Pull request closed without merging**
