### PR TITLE
Pcl & odk v1.2.32 release

### PR DESCRIPTION
**Pull request by hkir-dev**

### CODE REVIEW

**Comment by shawntanzk** [comment]
is this something we should be concerned about (in BDS-full) 
Screenshot 2022-01-14 at 13 00 00

**Comment by hkir-dev** [comment]
Seems those are coming from PR. It is the value of has_gene_template property

**Comment by shawntanzk** [comment]
> Seems those are coming from PR. It is the value of has_gene_template property

weird, hmmm, let me check if it is important, if not can we remove it?

**Comment by shawntanzk** [comment]
hmmm strange, just checked, and the import should have excluded those (it is declared under exclude_iri_patterns in bdso-odk.yaml)

**Comment by shawntanzk** [comment]
@hkir-dev actually its not a big deal, since BDSO isn't front facing, and bdso-base-ext seems to be fine, its not a real issue

**Review by shawntanzk — APPROVED** [review]

**Comment by hkir-dev** [comment]
This can be a bug in odk. Seems `exclude_iri_patterns` only effect, merged_import.owl (not other imports). For this purpose CL manually override all import goals to add related Robot remove commands (such as https://github.com/obophenotype/cell-ontology/blob/6b4ec418bb722e28e1086b106e49b93b4aee3c4c/src/ontology/cl.Makefile#L286).

Applied the same approach, seems they are disappeared.

**Comment by shawntanzk** [comment]
@hkir-dev looks good :)

**Pull request merged**
